/*
    HovSound.h
    Generated by FMOD Designer v4.28.7 
*/

#ifndef HOVSOUND_H
#define HOVSOUND_H

/*
    Total number of events in the project
*/
const int EVENTCOUNT_HOVSOUND = 1;

/*
    EventGroup/Event-relative indices
*/
const int EVENTGROUP_HOVSOUND_UNTITLED = 0;
const int EVENTGROUPCOUNT_HOVSOUND_UNTITLED = 1;
const int EVENT_HOVSOUND_UNTITLED_EVENT00 = 0;

/*
    Project-unique event ids
*/
const int EVENTID_HOVSOUND_UNTITLED_EVENT00 = 0;

const int EVENTCATEGORY_HOVSOUND_MASTER = 0;
const int EVENTCATEGORYCOUNT_HOVSOUND_MASTER = 1;

const int EVENTCATEGORY_HOVSOUND_MASTER_MUSIC = 0;
const int EVENTCATEGORYCOUNT_HOVSOUND_MASTER_MUSIC = 0;


/*
    Event GUIDs
*/
const char *EVENTGUID_HOVSOUND_UNTITLED_EVENT00 = "{b866f68f-10e9-4ab3-9aa2-438c220f6fc0}";

/*
    Music cue ids
*/
const unsigned int MUSICCUE_HOVSOUND_BACKGROUND_NORMAL = 2;

#endif /* HOVSOUND_H */
