/*
    HovSound.h
    Generated by FMOD Designer v4.28.7 
*/

#ifndef HOVSOUND_H
#define HOVSOUND_H

/*
    Total number of events in the project
*/
const static int EVENTCOUNT_HOVSOUND = 1;

/*
    EventGroup/Event-relative indices
*/
const static int EVENTGROUP_HOVSOUND_EVENTS = 0;
const static int EVENTGROUPCOUNT_HOVSOUND_EVENTS = 1;
const static int EVENT_HOVSOUND_EVENTS_HOVERCRAFT = 0;
const static int EVENTPARAMETER_HOVSOUND_EVENTS_HOVERCRAFT_RPM = 0;
const static int EVENTPARAMETER_HOVSOUND_EVENTS_HOVERCRAFT_LOAD = 1;

/*
    Project-unique event ids
*/
const static int EVENTID_HOVSOUND_EVENTS_HOVERCRAFT = 0;

const static int EVENTCATEGORY_HOVSOUND_MASTER = 0;
const static int EVENTCATEGORYCOUNT_HOVSOUND_MASTER = 1;

const static int EVENTCATEGORY_HOVSOUND_MASTER_MUSIC = 0;
const static int EVENTCATEGORYCOUNT_HOVSOUND_MASTER_MUSIC = 0;


/*
    Event GUIDs
*/
const static char *EVENTGUID_HOVSOUND_EVENTS_HOVERCRAFT = "{b35c1ac9-f834-4c7c-919e-4e80d98d6483}";

/*
    Music cue ids
*/
const static unsigned int MUSICCUE_HOVSOUND_BACKGROUND_NORMAL = 2;
const static unsigned int MUSICCUE_HOVSOUND_MENU = 3;

#endif /* HOVSOUND_H */
